"""initial migration

Revision ID: 28cb6cd90b3c
Revises: 
Create Date: 2025-03-20 16:02:54.293029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cb6cd90b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_word')
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('meaning', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('example', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('learned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('success_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.Integer(), nullable=True))
        batch_op.alter_column('pronunciation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('mastered')
        batch_op.drop_column('example_sentences')
        batch_op.drop_column('word_type')
        batch_op.drop_column('review')
        batch_op.drop_column('english')
        batch_op.drop_column('turkish')
        batch_op.drop_column('added_by')
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('added_by', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('turkish', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('english', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('review', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('word_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('example_sentences', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('mastered', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pronunciation',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('success_rate')
        batch_op.drop_column('review_count')
        batch_op.drop_column('last_reviewed')
        batch_op.drop_column('learned')
        batch_op.drop_column('user_id')
        batch_op.drop_column('example')
        batch_op.drop_column('meaning')
        batch_op.drop_column('word')

    op.create_table('_alembic_tmp_word',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('meaning', sa.VARCHAR(length=200), nullable=False),
    sa.Column('example', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('learned', sa.BOOLEAN(), nullable=True),
    sa.Column('last_reviewed', sa.DATETIME(), nullable=True),
    sa.Column('review_count', sa.INTEGER(), nullable=True),
    sa.Column('success_rate', sa.FLOAT(), nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('pronunciation', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_word_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
